name: Docker Excercise 1 Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        # Navigate to the desired directory
        cd ./04-containers/exercise1/
        # Build the Docker 
        docker build . --file Dockerfile --tag bios259:$(date +%s)
